# Generated by Django 4.2.2 on 2024-03-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('student_photo', models.ImageField(upload_to='')),
                ('gender', models.BooleanField()),
                ('dob', models.DateField()),
                ('aadhar_no', models.IntegerField()),
                ('roll_no', models.IntegerField(unique=True)),
                ('register_no', models.IntegerField(unique=True)),
                ('admission_year', models.IntegerField()),
                ('academic_year', models.IntegerField()),
                ('religion', models.CharField(max_length=25)),
                ('caste', models.CharField(max_length=25)),
                ('sub_caste', models.CharField(max_length=25)),
                ('nationality', models.CharField(max_length=25)),
                ('mother_tongue', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('taluka', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=250)),
                ('class_no', models.IntegerField()),
                ('class_division', models.CharField(max_length=4)),
            ],
        ),
    ]
