# Generated by Django 4.2.2 on 2024-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1),
        ),
    ]
