# Generated by Django 4.2.2 on 2024-04-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_surname_studentinfo_student_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_middle_name', models.CharField(max_length=50)),
                ('teacher_surname', models.CharField(max_length=50)),
                ('teacher_registration_number', models.PositiveIntegerField()),
                ('teacher_address', models.CharField(max_length=250)),
                ('teacher_contact_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='aadhar_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='academic_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='class_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='register_no',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='roll_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
