# Generated by Django 4.2.2 on 2024-04-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_teacherinfo_alter_studentinfo_aadhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
