# Generated by Django 4.2.2 on 2024-04-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_teacherinfo_teacher_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='student_surname',
            new_name='students_surname',
        ),
    ]
