# Generated by Django 4.2.2 on 2024-04-03 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0011_alter_studentinfo_user_alter_teacherinfo_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together={('user', 'roll_no', 'register_no')},
        ),
    ]
