# Generated by Django 4.2.2 on 2024-04-20 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0013_alter_studentinfo_register_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='aadhar_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='caste',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='nationality',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='qualificatons',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='religion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='sub_caste',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='taluka',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='teacher_unique_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teacherinfo',
            unique_together={('user', 'teacher_unique_id', 'teacher_registration_number')},
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='teacher_address',
        ),
    ]
