# Generated by Django 4.2.2 on 2024-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_teacherinfo_aadhar_no_teacherinfo_caste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='teaacher_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
