# Generated by Django 4.2.2 on 2024-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_studentmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='what_division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='class_division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
