# Generated by Django 5.0.4 on 2024-04-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_rename_what_division_studentmarks_class_division_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherinfo',
            old_name='qualificatons',
            new_name='qualifications',
        ),
        migrations.RenameField(
            model_name='teacherinfo',
            old_name='teaacher_photo',
            new_name='teacher_photo',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='street_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
